Fixed bottomBar Slide Animation
fossasia/phimpme-android pull request #2925
Opened 2019-11-18 20:09 UTC by satyajiit

Fixed #2923 

Changes: Added a global variable to MyApplication Class.
And applied transition based on logic/conditions to each of the three activities.
Since we have three NavItems NavItem starts from zero to two.
Added four new anim xml files and deleted the old two.

GIF :
![gif](https://user-images.githubusercontent.com/41864109/69039222-80cf1c00-0a11-11ea-96ed-257e1460b0c8.gif)

Thank you @codedsun for your valuable feedback and review on this issue. 🙂

2019-11-18 20:12 UTC, satyajiit commented on app/src/main/java/org/fossasia/phimpme/opencamera/Camera/CameraActivity.java
> +    startSlideAnimation(0);
Zero Marks the Start Position of NavItem i.e Camera

2019-11-18 20:13 UTC, satyajiit commented on app/src/main/res/anim/left_to_right.xml
> -<?xml version="1.0" encoding="utf-8"?>
Not Required

2019-11-20 18:09 UTC, rob729 reviewed
@satyajiit Squash these commits into a single commit

2019-11-20 20:08 UTC, satyajiit commented
@rob729 is it fine now?
Or should i start a new PR?

2019-11-21 04:18 UTC, yashk2000 approved these changes

2019-11-22 06:11 UTC, codedsun requested changes
Use base activity instead of application class

2026-06-10 10:48 UTC, closed without merging