Searching and Sorting Fix along with name to root folder
fossasia/phimpme-android pull request #2928
Opened 2019-11-19 01:16 UTC by satyajiit

Fixed #2926

Changes: Images stored in Root directory or /sdcard now won't show or store null value as name.
As a result doing search and sorting ,
there would be no crash or termination since we are giving a name to the folder in case of that image is stored in "/sdcard".

Screenshots of the change: 
Before 
![before](https://user-images.githubusercontent.com/41864109/69107621-fb427f00-0a97-11ea-9d97-3bfb9998bf2d.jpg)
After 
![after](https://user-images.githubusercontent.com/41864109/69107626-009fc980-0a98-11ea-9408-d855a97ccb09.jpg)

This fixed the search issue which was also causing crash on sorting since we had a null value.

2019-11-20 18:37 UTC, rob729 reviewed
@satyajiit Squash these commits into a single commit

2019-12-22 09:40 UTC, codedsun commented
@satyajiit please do the changes

2020-01-07 16:06 UTC, codedsun requested changes
@satyajiit  - Please do the changes

2020-04-10 16:27 UTC, iamareebjamal approved these changes

2020-10-12 09:39 UTC, iamareebjamal commented
@satyajiit Please resolve the conflicts

2026-06-10 10:48 UTC, closed without merging