i have added resize buttons in StickerItem.java,TextStickerView.java …
fossasia/phimpme-android pull request #3090
Opened 2020-10-04 19:38 UTC by SunitRoy2703

Fixed #3041 

Changes: I have added resize buttons in StickerItem.java,TextStickerView.java,  which will make the App more user-friendly

Screenshots of the change:
StickerItem

 ![Screenshot_2020-10-05-00-54-18-13_e9fa3137047667733754e6d84fae6a64 1](https://user-images.githubusercontent.com/67560900/95025358-bd961700-06a6-11eb-8fd5-fb89d54ab0f6.jpg)

TextSticker

![Screenshot_2020-10-05-00-52-45-74_e9fa3137047667733754e6d84fae6a64 1](https://user-images.githubusercontent.com/67560900/95025401-1b2a6380-06a7-11eb-8939-325fc475d9db.jpg)

2020-10-05 03:20 UTC, abishekvashok requested changes
Although it does seem nice, can you use a vector instead of a bitmap since the image shown is small.

2020-10-05 06:03 UTC, SunitRoy2703 commented
> Although it does seem nice, can you use a vector instead of a bitmap since the image shown is small.

I tried vector images at first, But All the code is written for taking a bitmap and the previous image and all the other images are in Bitmao.

2020-10-06 13:05 UTC, SunitRoy2703 commented
@mariobehling plz review

2020-10-12 07:49 UTC, SunitRoy2703 commented
@iamareebjamal can you plz review

2020-10-26 03:02 UTC, mariobehling requested changes
Pretty nice, but we cannot move forward with failing builds. Please check Travis and fix the build. Thank you.

2026-06-10 10:48 UTC, closed without merging