feature- standard gallery UI
fossasia/phimpme-android pull request #3098
Opened 2020-10-06 23:10 UTC by SunitRoy2703

Fixed #2921 

Changes: 
        1. Removed media word after the counting of photos, because no normal gallery App writes media after the counting
         2. Differentiated the font and color of both album name and count.
        3. changed the font and color of both album name and count.
        4. Made the background of the textview and the theme same to make it look clean.
        5.Made the edges of the imageview rounded to give it a complete feel.

pictures of Android galleries:
![1](https://user-images.githubusercontent.com/67560900/95263385-55cd0100-084b-11eb-9285-b83e8fe94a19.jpg)
![2](https://user-images.githubusercontent.com/67560900/95263420-5ebdd280-084b-11eb-97d7-ee22a077a403.jpg)

Before the change: 
![Project Name](https://user-images.githubusercontent.com/67560900/95265821-9f1f4f80-084f-11eb-87ff-69ff6fa68a04.gif)

After the change:

![Project Name (4)](https://user-images.githubusercontent.com/67560900/95269404-f117a380-0856-11eb-84ce-e1c180f63a7a.gif)

2020-10-12 07:50 UTC, SunitRoy2703 commented
@iamareebjamal sir plz review

2020-10-12 09:36 UTC, iamareebjamal commented
Build is failing

2020-10-26 02:59 UTC, mariobehling requested changes
* Please do not change the color scheme of the app from blue to something else.
* Please fix failing build

2020-11-28 10:17 UTC, SunitRoy2703 commented
@iamareebjamal @mariobehling  
Sir whole development branch build is failing.

2026-06-10 10:48 UTC, closed without merging